### ISSUE TITLE
Clean up Kernel Specs

### ISSUE THREAD

**Issue by blink1073** [jupyterlab/services#259]
Kernel specs in [nbformat](https://github.com/jupyter/nbformat/blob/master/nbformat/v4/nbformat.v4.schema.json)  consist of a `name` and `display_name`.
Kernel specs in jupyter_client [docs](https://jupyter-client.readthedocs.io/en/latest/kernels.html) consist of: `argv`, `display_name`, `language` and `env` (optional).
Kernel specs returned by the the [server](https://github.com/jupyter/notebook/blob/master/notebook/services/kernelspecs/handlers.py) include:
`default`: string
`kernelspecs`: `{ key: model }`

Where `model` is:
`name`: string, `spec`: jupyter_client spec, and `resources`

I think we should flatten the client side representation to:

```typescript
interface IKernelSpecs {
  default: string;
  values: { [key: string]: IKernelSpec }
}

interface IKernelspec {
  name: string;
  display_name: string;
  argv: string[];
  language: string;
  env: { [key: string]: string },
  resources: { [key: string]: string }
}
```

This would  change `kernelspecs.kernelspecs['foo'].spec.display_name` to `kernelspecs.values['foo'].display_name`

**Comment by blink1073** [comment]
cc @minrk

**Comment by minrk** [comment]
Sounds good to me if it helps. There is a distinction in this information though:

- a kernelspec is a directory containing files
- the name of that directory identifies which kernelspec it is (`name`), and is not part of the spec itself
- in that directory is a `kernel.json` containing some information, represented in the API as `spec`.
- in that directory may also be logo files, kernel.js, etc. identified as `resources`

In this way, `spec` really is a sibling of `resources`. But if flattening improves the experience over the current situation, go for it! Do you think we should do a similar flattening in the REST API?

**Comment by blink1073** [comment]
The way I read the [documentation](http://jupyter-client.readthedocs.io/en/latest/kernels.html#kernel-specs), I would view a kernelspec to be a union of all of that information.  It does not call out a `spec` for the `kernel.json` file.  I'd view that file as contributing the the kernel spec itself.  I'd be in favor of flattening it in the REST API.
