### ISSUE TITLE
How to handle custom kernel message types?

### ISSUE THREAD

**Issue by rolweber** [jupyterlab/services#316]
We're using kernels via notebooks and the kernel gateway to work with Apache Spark. In order to enable progress monitoring on Spark jobs, we implemented a custom kernel message type, `spark_monitor_msg`. The assumption was that clients not interested in these messages will not subscribe to them, so they don't pose a problem. But when I use the services library against kernel gateway, I get error messages on the console. Apparently, the [validation logic](https://github.com/jupyterlab/services/blob/master/src/kernel/validate.ts) doesn't allow for custom kernel message types.

    Invalid message: Invalid Kernel message: iopub message type spark_monitor_msg not recognized

Are the kernel messages a closed protocol that is not meant to be extended with custom message types? Is there a special namespace for custom message types that we should use, like "x-whatever"? Or should there be a way to customize the validation logic here to enable certain custom message types that a client is prepared for?

I'd appreciate your guidance in this matter.

**Comment by rolweber** [comment]
I found a messaging spec that says: "Both sides should allow unexpected message types, and extra fields in known message types, so that additions to the protocol do not break existing code."

http://jupyter-client.readthedocs.io/en/latest/messaging.html

**Comment by blink1073** [comment]
Yep, the validation logic needs to be updated.

**Comment by blink1073** [comment]
Released in `0.40.3`.
